export type QualityTool = {
  slug: string;
  name: string;
  category: string;
  summary: string;
  origin: string;
  why: string;
  useWhen: string[];
  sectors: string[];
  keywords: string[];
};

export type ProblemGuide = {
  problem: string;
  context: string;
  outcome: string;
  toolSlugs: string[];
  keywords: string[];
};

export const sectors = [
  "Todos",
  "Atendimento",
  "Vendas",
  "E-commerce",
  "SaaS e tecnologia",
  "Projetos",
  "Riscos",
  "Pessoas",
  "Operações",
];

export const qualityTools: QualityTool[] = [
  {
    slug: "fluxograma",
    name: "Fluxograma",
    category: "Processos",
    summary: "Representa as etapas e decisões de um processo para revelar falhas, esperas e retrabalho.",
    origin: "Frank e Lillian Gilbreth apresentaram o gráfico de processo à ASME em 1921. A notação evoluiu depois.",
    why: "Tornar o trabalho real visível antes de tentar padronizar ou melhorar.",
    useWhen: ["Ninguém concorda sobre como o processo funciona", "Há etapas duplicadas, demora ou repasse excessivo", "É preciso treinar ou documentar um fluxo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["comunicação", "passagem de bastão", "jornada", "funil", "checkout", "processo desorganizado", "retrabalho", "implantação"],
  },
  {
    slug: "ishikawa",
    name: "Diagrama de Ishikawa",
    category: "Causa raiz",
    summary: "Organiza causas possíveis de um efeito em grupos para orientar uma investigação baseada em evidências.",
    origin: "Associado a Kaoru Ishikawa e difundido no Japão a partir da década de 1940.",
    why: "Evitar soluções apressadas que tratam apenas o sintoma.",
    useWhen: ["Um erro se repete", "Há muitas hipóteses sobre a causa", "Uma falha envolve pessoas, método, tecnologia ou ambiente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["comunicação", "cliente insatisfeito", "queda de vendas", "turnover", "falha", "erro", "causa", "6m"],
  },
  {
    slug: "folha-verificacao",
    name: "Folha de verificação",
    category: "Coleta de dados",
    summary: "Registra ocorrências no momento em que acontecem usando categorias consistentes e fáceis de contar.",
    origin: "Consolidada entre as sete ferramentas básicas da qualidade no século XX. Não há um único criador consensual.",
    why: "Transformar percepções soltas em dados comparáveis.",
    useWhen: ["Você precisa saber quantas vezes algo acontece", "Os dados vêm de várias pessoas", "É necessário preparar uma análise de Pareto"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Riscos", "Pessoas", "Operações"],
    keywords: ["medição", "contagem", "ocorrência", "elogio", "reclamação", "motivo de contato", "perda de cliente", "dados"],
  },
  {
    slug: "pareto",
    name: "Diagrama de Pareto",
    category: "Priorização",
    summary: "Ordena causas ou ocorrências por frequência ou impacto e mostra o percentual acumulado.",
    origin: "Joseph Juran aplicou o princípio de Pareto à gestão da qualidade em meados do século XX.",
    why: "Concentrar esforço nas poucas causas que respondem pela maior parte do efeito.",
    useWhen: ["Há problemas demais para tratar ao mesmo tempo", "Você quer priorizar motivos de perda ou reclamação", "Precisa justificar uma prioridade com números"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["vendas", "perda de cliente", "churn", "cancelamento", "reclamação", "defeito", "80 20", "prioridade", "atraso"],
  },
  {
    slug: "histograma",
    name: "Histograma",
    category: "Estatística",
    summary: "Mostra como valores numéricos se distribuem por faixas, revelando concentração, dispersão e assimetria.",
    origin: "Karl Pearson introduziu o termo histograma em 1895.",
    why: "Entender a forma e a variação dos dados antes de concluir pela média.",
    useWhen: ["Você tem muitos valores numéricos", "Quer comparar tempo, nota, ticket ou produtividade", "Precisa verificar dispersão e valores extremos"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["estatística", "número", "dados", "distribuição", "tempo médio", "nota", "ticket médio", "produtividade", "medição"],
  },
  {
    slug: "carta-controle",
    name: "Carta de controle",
    category: "Estatística",
    summary: "Acompanha uma medida no tempo e diferencia variação comum de sinais que exigem investigação.",
    origin: "Walter A. Shewhart desenvolveu os gráficos de controle nos Bell Labs na década de 1920.",
    why: "Controlar processos com base em comportamento ao longo do tempo, sem reagir a cada oscilação isolada.",
    useWhen: ["É preciso saber se o processo está estável", "Você acompanha uma métrica por semana ou mês", "Quer verificar se uma melhoria permaneceu"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Operações"],
    keywords: ["estatística", "indicador", "tendência", "meta", "variação", "tempo", "conversão", "qualidade", "estabilidade"],
  },
  {
    slug: "dispersao",
    name: "Diagrama de dispersão",
    category: "Estatística",
    summary: "Compara pares de valores para investigar se duas variáveis parecem se mover juntas.",
    origin: "Deriva dos estudos de correlação do fim do século XIX, associados a Francis Galton e Karl Pearson.",
    why: "Testar uma hipótese de relação antes de afirmar causa e efeito.",
    useWhen: ["Você suspeita que uma variável influencia outra", "Quer comparar treinamento e desempenho", "Precisa investigar preço, prazo, satisfação ou conversão"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["correlação", "vendas", "satisfação", "conversão", "treinamento", "produtividade", "estatística", "dados", "churn"],
  },
  {
    slug: "sipoc",
    name: "SIPOC",
    category: "Processos",
    summary: "Delimita fornecedores, entradas, processo, saídas e clientes em uma visão de alto nível.",
    origin: "Difundido por programas de melhoria de processos e Six Sigma no fim do século XX.",
    why: "Alinhar rapidamente o escopo e as interfaces antes de detalhar o processo.",
    useWhen: ["Um projeto começa sem escopo claro", "Há conflito entre áreas", "Você precisa entender quem entrega o quê para quem"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["comunicação entre áreas", "handoff", "fornecedor", "cliente", "escopo", "implantação", "processo"],
  },
  {
    slug: "kanban",
    name: "Kanban",
    category: "Fluxo de trabalho",
    summary: "Visualiza demandas em andamento e limita trabalho simultâneo para melhorar fluxo e previsibilidade.",
    origin: "Taiichi Ohno desenvolveu o sistema kanban na Toyota entre as décadas de 1940 e 1950.",
    why: "Expor filas, bloqueios e excesso de trabalho iniciado.",
    useWhen: ["Existem tarefas paradas ou esquecidas", "A equipe inicia mais do que consegue terminar", "Falta visibilidade de prazos e responsáveis"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["tarefa", "prazo", "fila", "backlog", "projeto", "atendimento", "organização", "comunicação"],
  },
  {
    slug: "5s",
    name: "5S",
    category: "Organização",
    summary: "Cria disciplina para separar, ordenar, limpar, padronizar e sustentar um ambiente de trabalho.",
    origin: "Sistematizado no Japão do pós-guerra. A literatura não atribui uma única data ou autoria.",
    why: "Reduzir perdas causadas por desorganização física ou digital.",
    useWhen: ["Documentos e informações são difíceis de encontrar", "O ambiente causa erros ou desperdício", "Uma equipe precisa de padrões simples de organização"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["organização", "documentos", "arquivos", "ambiente", "padronização", "desperdício"],
  },
  {
    slug: "matriz-risco",
    name: "Matriz de risco",
    category: "Riscos",
    summary: "Classifica riscos combinando probabilidade e impacto para orientar resposta e prioridade.",
    origin: "Consolidada em segurança, defesa e engenharia ao longo do século XX, com diversas versões.",
    why: "Dar um critério comum para decidir quais incertezas exigem ação.",
    useWhen: ["Um projeto ou mudança ainda não começou", "Há riscos operacionais ou de segurança", "É preciso decidir entre aceitar, mitigar, transferir ou evitar"],
    sectors: ["E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["risco", "projeto", "implantação", "segurança", "impacto", "probabilidade", "prevenção", "fornecedor"],
  },
  {
    slug: "pfmea",
    name: "PFMEA",
    category: "Riscos",
    summary: "Analisa modos de falha de um processo, seus efeitos, causas, controles atuais e ações preventivas.",
    origin: "FMEA surgiu em aplicações militares e aeroespaciais do pós-guerra. A variante de processo se difundiu depois na indústria automotiva.",
    why: "Prevenir falhas antes que cheguem ao cliente ou interrompam a operação.",
    useWhen: ["Você desenha ou altera um processo", "Uma falha pode ter alto impacto", "É preciso revisar controles preventivos e de detecção"],
    sectors: ["E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["falha", "risco", "e-commerce", "checkout", "implantação", "severidade", "ocorrência", "detecção"],
  },
  {
    slug: "5-porques",
    name: "5 Porquês",
    category: "Causa raiz",
    summary: "Aprofunda uma cadeia causal perguntando por que o problema aconteceu até chegar a uma causa tratável.",
    origin: "Associado ao Sistema Toyota de Produção e ao trabalho de Taiichi Ohno no século XX.",
    why: "Sair da explicação superficial e encontrar uma ação que evite recorrência.",
    useWhen: ["O problema é específico e a equipe conhece o processo", "Uma ocorrência se repete", "Você precisa de uma investigação inicial rápida"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["comunicação", "causa raiz", "erro", "reclamação", "perda de cliente", "turnover", "atraso", "falha"],
  },
  {
    slug: "5w2h",
    name: "5W2H",
    category: "Plano de ação",
    summary: "Converte uma decisão em ação ao definir o que, por que, onde, quando, quem, como e quanto custa.",
    origin: "Técnica de planejamento difundida no século XX. A origem exata não é consensual.",
    why: "Eliminar planos vagos, sem dono, prazo ou modo de execução.",
    useWhen: ["A equipe já entendeu a causa e precisa agir", "Há dúvidas sobre responsabilidade ou prazo", "Um projeto precisa de um plano simples"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["plano de ação", "responsável", "prazo", "custo", "projeto", "melhoria", "implantação", "vendas"],
  },
  {
    slug: "masp",
    name: "MASP",
    category: "Solução de problemas",
    summary: "Estrutura a identificação, análise, ação, verificação e padronização da solução de um problema.",
    origin: "Adaptação brasileira do QC Story, difundida a partir da década de 1980.",
    why: "Conduzir problemas relevantes com disciplina e registro do aprendizado.",
    useWhen: ["O problema exige investigação completa", "Várias áreas participam da solução", "É necessário comprovar eficácia e padronizar"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["problema", "causa", "ação corretiva", "melhoria", "resultado", "padronização", "reclamação"],
  },
  {
    slug: "dmaic",
    name: "DMAIC",
    category: "Melhoria de processos",
    summary: "Organiza projetos em definir, medir, analisar, melhorar e controlar, com uso disciplinado de dados.",
    origin: "Ligado ao Six Sigma da Motorola nos anos 1980 e difundido amplamente nos anos 1990.",
    why: "Melhorar processos existentes quando o problema e o desempenho precisam ser quantificados.",
    useWhen: ["Há impacto mensurável e dados disponíveis", "A causa ainda não está comprovada", "A melhoria precisa ser sustentada por controles"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["dados", "estatística", "vendas", "conversão", "tempo", "defeito", "melhoria", "six sigma"],
  },
  {
    slug: "pdca",
    name: "PDCA",
    category: "Melhoria contínua",
    summary: "Cria um ciclo de planejar, executar, verificar resultados e agir para ajustar ou padronizar.",
    origin: "Deriva do ciclo de Shewhart dos anos 1930 e ganhou projeção com W. Edwards Deming.",
    why: "Transformar melhoria em um processo contínuo de teste e aprendizado.",
    useWhen: ["Você precisa testar uma melhoria", "Existe uma meta e um indicador", "A solução precisa virar padrão"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["melhoria", "indicador", "meta", "teste", "plano", "resultado", "padronização", "qualidade"],
  },
  {
    slug: "a3",
    name: "Kaizen A3",
    category: "Melhoria contínua",
    summary: "Registra contexto, análise, objetivo, contramedidas e acompanhamento de uma melhoria em uma narrativa concisa.",
    origin: "Desenvolvido na Toyota e nomeado pelo formato de papel A3 usado para comunicar o raciocínio.",
    why: "Tornar o pensamento por trás da melhoria claro e compartilhável.",
    useWhen: ["É preciso alinhar liderança e equipe", "O problema cabe em um projeto de melhoria focado", "Você quer registrar decisão e acompanhamento"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["kaizen", "melhoria", "comunicação", "projeto", "relatório", "causa", "plano"],
  },
  {
    slug: "gut",
    name: "Matriz GUT",
    category: "Priorização",
    summary: "Compara problemas por gravidade, urgência e tendência usando uma escala comum.",
    origin: "Popular na gestão brasileira. A atribuição histórica varia e não há origem única bem documentada.",
    why: "Criar uma ordem de ataque quando diferentes problemas competem por atenção.",
    useWhen: ["Tudo parece urgente", "A equipe precisa negociar prioridades", "Há riscos ou problemas qualitativos difíceis de comparar"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["prioridade", "urgência", "gravidade", "risco", "problema", "backlog", "plano"],
  },
  {
    slug: "bsc",
    name: "Balanced Scorecard",
    category: "Estratégia e indicadores",
    summary: "Conecta objetivos, indicadores, metas e iniciativas nas perspectivas financeira, clientes, processos e aprendizado.",
    origin: "Robert Kaplan e David Norton apresentaram o Balanced Scorecard em 1992.",
    why: "Traduzir estratégia em medidas equilibradas, além do resultado financeiro isolado.",
    useWhen: ["A empresa precisa alinhar indicadores à estratégia", "Há métricas sem relação clara com objetivos", "A liderança quer acompanhar execução de longo prazo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["indicador", "kpi", "vendas", "cliente", "financeiro", "estratégia", "meta", "medição"],
  },
  {
    slug: "indicadores",
    name: "Indicadores de qualidade",
    category: "Medição",
    summary: "Traduzem objetivos em medidas com fórmula, fonte, frequência, responsável e interpretação definidas.",
    origin: "Prática consolidada em gestão e controle ao longo do século XX, sem um único criador.",
    why: "Acompanhar desempenho e tomar decisões usando critérios consistentes.",
    useWhen: ["Uma meta está vaga", "Você precisa demonstrar evolução", "A equipe coleta números mas não sabe o que eles significam"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["medição", "kpi", "número", "dados", "meta", "conversão", "satisfação", "churn", "tempo", "estatística"],
  },
  {
    slug: "qfd",
    name: "QFD",
    category: "Cliente e produto",
    summary: "Converte necessidades do cliente em requisitos técnicos e prioridades de produto ou serviço.",
    origin: "Desenvolvido no Japão no fim dos anos 1960 por Yoji Akao e Shigeru Mizuno.",
    why: "Evitar que a solução técnica se afaste do que o cliente realmente valoriza.",
    useWhen: ["Você desenha um produto ou serviço", "Clientes reclamam de aspectos diferentes", "É preciso priorizar requisitos a partir da voz do cliente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos"],
    keywords: ["cliente", "vendas", "satisfação", "necessidade", "produto", "requisito", "experiência", "pesquisa"],
  },
  {
    slug: "8d",
    name: "8D",
    category: "Solução de problemas",
    summary: "Conduz resposta em equipe, contenção, causa raiz, correção, prevenção e reconhecimento do aprendizado.",
    origin: "Popularizado pela Ford na década de 1980, com raízes em práticas anteriores de resolução estruturada.",
    why: "Controlar rapidamente um problema relevante sem abandonar a investigação definitiva.",
    useWhen: ["O cliente sofre impacto agora", "É necessária contenção imediata", "O problema é complexo e recorrente"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["reclamação", "incidente", "contenção", "falha", "cliente", "ação corretiva", "recorrência"],
  },
  {
    slug: "msa",
    name: "MSA e estudo R&R",
    category: "Medição",
    summary: "Avalia se o sistema de medição produz resultados consistentes entre pessoas, instrumentos e repetições.",
    origin: "Consolidado na indústria automotiva e em manuais de análise de sistemas de medição no fim do século XX.",
    why: "Separar variação real do processo da variação criada pela própria medição.",
    useWhen: ["A equipe não confia nas notas ou avaliações", "Avaliadores discordam muito", "Um indicador depende de julgamento ou instrumento"],
    sectors: ["Atendimento", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["calibragem", "avaliação", "nota", "medição", "concordância", "dados", "estatística", "auditoria"],
  },
  {
    slug: "fmea-poka-yoke",
    name: "Poka-yoke",
    category: "Prevenção de erros",
    summary: "Usa mecanismos simples para impedir um erro ou torná-lo imediatamente visível.",
    origin: "Associado a Shigeo Shingo e ao Sistema Toyota de Produção na década de 1960.",
    why: "Projetar o processo para reduzir dependência de atenção e memória.",
    useWhen: ["O mesmo erro humano reaparece", "Uma validação pode ser automatizada", "A falha precisa ser detectada antes de chegar ao cliente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Operações"],
    keywords: ["erro humano", "validação", "formulário", "sistema", "checkout", "prevenção", "automação"],
  },
  {
    slug: "qualidade-conceito",
    name: "Qualidade: o conceito completo",
    category: "Fundamentos",
    summary: "Qualidade é atender ou superar as expectativas do cliente somando conformidade, ausência de defeitos, durabilidade, confiabilidade e satisfação.",
    origin: "Evolução do controle da qualidade ao longo do século XX, da inspeção à qualidade total.",
    why: "Evitar reduzir qualidade a apenas satisfação: a entrega precisa cumprir requisitos e padrões.",
    useWhen: ["Cliente satisfeito, mas com retrabalho ou falha", "É preciso avaliar um produto ou serviço por critérios objetivos", "A equipe confunde qualidade com rapidez"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["conceito", "conformidade", "defeito", "durabilidade", "confiabilidade", "satisfação", "requisito", "padrão", "qualidade"],
  },
  {
    slug: "gestao-qualidade-visao-geral",
    name: "Gestão da qualidade: como funciona e onde funciona",
    category: "Fundamentos",
    summary: "Conjunto de práticas para planejar, controlar, monitorar e aperfeiçoar entregas. Evoluiu da inspeção ao controle estatístico, à garantia e à qualidade total.",
    origin: "Evolução histórica iniciada com o controle estatístico de Shewhart nos anos 1920 e consolidada no pós-guerra.",
    why: "Tirar a qualidade do improviso e transformá-la em gestão: processos, padrões, indicadores e melhoria contínua.",
    useWhen: ["A empresa não tem gestão de qualidade estruturada", "Qualquer setor: indústria, saúde, serviços, varejo, TI", "É preciso explicar qualidade para a direção"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["gestão", "sgq", "sistema de gestão", "inspeção", "prevenção", "melhoria", "conceito", "qualidade"],
  },
  {
    slug: "deming",
    name: "Deming e os 14 princípios",
    category: "Fundamentos",
    summary: "A qualidade depende do sistema e da gestão, não do esforço individual. 94% dos problemas vêm do sistema: constância de propósito, fim da inspeção em massa, eliminar o medo, treinamento e melhoria contínua.",
    origin: "W. Edwards Deming levou o controle estatístico ao Japão a partir de 1950 e provocou a revolução da qualidade japonesa.",
    why: "Diagnosticar se o problema é do sistema ou da gestão antes de culpar o operador.",
    useWhen: ["A equipe é culpada por falhas do processo", "Metas numéricas sem método geram pressão", "Barreiras entre departamentos travam o fluxo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["deming", "sistema", "gestão", "medo", "metas", "princípios", "cultura", "turnover", "liderança"],
  },
  {
    slug: "juran-trilogia",
    name: "Juran e a trilogia da qualidade",
    category: "Fundamentos",
    summary: "A qualidade se administra em três processos: planejamento (identificar clientes e necessidades), controle (acompanhar contra objetivos) e melhoria (alcançar níveis superiores).",
    origin: "Joseph Juran atuou no Japão a partir de 1954 e popularizou o princípio de Pareto na qualidade.",
    why: "Organizar a área de qualidade como sistema completo: não basta medir, é preciso planejar e melhorar.",
    useWhen: ["A área de qualidade só mede e não planeja", "É preciso organizar critérios, indicadores e planos", "Quero estruturar um ciclo avaliativo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["juran", "trilogia", "planejar", "controlar", "melhorar", "pareto", "prioridade", "qualidade"],
  },
  {
    slug: "crosby",
    name: "Crosby: zero defeitos e custo da não qualidade",
    category: "Fundamentos",
    summary: "Qualidade é conformidade com requisitos; a postura certa é prevenir, não inspecionar. Zero defeito é recusar erros como inevitáveis. O custo da não qualidade (retrabalho, devolução, perda de clientes) supera o custo da prevenção.",
    origin: "Philip Crosby publicou Quality is Free em 1979, após carreira industrial nos EUA.",
    why: "Justificar investimento em prevenção e mudar a cultura de aceitar erro como normal.",
    useWhen: ["A direção questiona investimento em qualidade", "Erros são tratados como parte do processo", "Preciso provar que prevenir custa menos que corrigir"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["crosby", "zero defeito", "prevenção", "custo da não qualidade", "retrabalho", "inspeção", "requisito", "qualidade"],
  },
  {
    slug: "ishikawa-fundamentos",
    name: "Ishikawa: círculos de qualidade e as 7 ferramentas",
    category: "Fundamentos",
    summary: "Quem executa o processo conhece os problemas melhor que a gerência. Formulou as 7 ferramentas da qualidade e difundiu os círculos de controle da qualidade (CCQ): grupos de trabalhadores que identificam e resolvem problemas.",
    origin: "Kaoru Ishikawa, químico japonês, nas décadas de 1950-60.",
    why: "Levar a melhoria ao chão de operação com ferramentas simples, não só a relatórios de gerência.",
    useWhen: ["As melhorias não saem dos relatórios", "A operação tem conhecimento que a gerência não vê", "Quero envolver a equipe na identificação de problemas"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["ishikawa", "ccq", "círculos", "participação", "colaboradores", "ferramentas básicas", "qualidade"],
  },
  {
    slug: "feigenbaum",
    name: "Feigenbaum e o controle da qualidade total",
    category: "Fundamentos",
    summary: "A qualidade não é responsabilidade de um departamento: compras, produção, engenharia, logística, vendas e atendimento participam. Nenhuma inspeção final resolve matéria-prima ruim ou processo instável.",
    origin: "Armand Feigenbaum propôs o Total Quality Control (TQC) em 1951, base do TQM.",
    why: "Quebrar a ilha da qualidade: quando só a equipe de qualidade se preocupa com qualidade.",
    useWhen: ["A qualidade está isolada em uma equipe", "Outras áreas acham qualidade problema dos inspetores", "Falhas atravessam vários setores"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["feigenbaum", "tqc", "qualidade total", "todos", "departamento", "cultura", "responsabilidade"],
  },
  {
    slug: "taguchi",
    name: "Taguchi e a função perda",
    category: "Fundamentos",
    summary: "Qualquer desvio do valor ideal gera perda, mesmo dentro das especificações. O objetivo é acertar o alvo com o mínimo de variação, base da redução de variabilidade defendida pelo Six Sigma.",
    origin: "Genichi Taguchi, engenheiro e estatístico japonês do século XX.",
    why: "Atacar resultados medianos: estar dentro da tolerância não basta para a percepção do cliente.",
    useWhen: ["O processo está dentro da tolerância, mas o cliente reclama de inconsistência", "Notas medianas se repetem sem defeito grave", "Quero reduzir variação de entrega"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["taguchi", "função perda", "variação", "variabilidade", "alvo", "especificação", "six sigma", "consistência"],
  },
  {
    slug: "implantar-gestao-qualidade",
    name: "Implantar gestão da qualidade passo a passo",
    category: "Fundamentos",
    summary: "Roteiro universal: alinhamento da direção, diagnóstico, objetivos mensuráveis, escolha de metodologia adequada ao porte, padronização do que é crítico, capacitação, PDCA como rotina e medição contínua.",
    origin: "Consolidado na prática da gestão da qualidade a partir dos anos 1980-90.",
    why: "Começar certo: sem alinhamento da direção, qualidade vira campanha temporária.",
    useWhen: ["A empresa começa do zero em qualidade", "Uma área de qualidade cresceu desordenada", "Preciso de um plano de implantação"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["implantar", "implantação", "começar", "passo a passo", "roteiro", "gestão", "qualidade", "estruturação"],
  },
  {
    slug: "excelencia-organizacional",
    name: "Excelência organizacional",
    category: "Fundamentos",
    summary: "Desempenho superior e sustentável, não apenas bater uma meta isolada. Envolve eficiência, liderança, inovação, melhoria contínua, foco no cliente, responsabilidade social e compromisso com a qualidade.",
    origin: "Conceito consolidado na literatura de gestão da qualidade no final do século XX.",
    why: "Resultado bom em um mês pode ser frágil: sobrecarga e dependência de uma pessoa não se sustentam.",
    useWhen: ["O resultado veio de sobrecarga ou improviso", "A operação depende de uma pessoa-chave", "Preciso avaliar se o desempenho se sustenta"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["excelência", "sustentável", "resultado", "desempenho", "meta", "sobrecarga", "turnover", "gestão"],
  },
  {
    slug: "enfoque-sistemico",
    name: "Enfoque sistêmico",
    category: "Fundamentos",
    summary: "A organização é um todo integrado: as partes interagem. Onde o problema aparece não é necessariamente onde começa. Sintoma é o efeito; causa é o que o produz e precisa ser investigado.",
    origin: "Abordagem sistêmica aplicada à gestão da qualidade ao longo do século XX.",
    why: "Evitar soluções no ponto errado: o indicador mostra onde apareceu, não onde começou.",
    useWhen: ["A queda de satisfação é atribuída ao atendimento sem investigar o sistema", "Uma mudança melhora um indicador e piora outro", "Problemas atravessam áreas"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["sistêmico", "sistema", "causa", "sintoma", "interdependência", "conexão", "gargalo", "processo"],
  },
  {
    slug: "eficiencia-eficacia",
    name: "Eficiência × eficácia",
    category: "Fundamentos",
    summary: "Eficiência é usar bem os recursos (como fiz?); eficácia é alcançar o resultado esperado (consegui?). Um processo pode ser rápido e barato sem resolver o problema do cliente.",
    origin: "Distinção clássica da administração, incorporada à gestão da qualidade.",
    why: "Otimizar velocidade às custas da resolução destrói valor: medir os dois separadamente.",
    useWhen: ["Chamados são encerrados rápido, mas o cliente volta", "Produtividade sobe e qualidade cai", "Preciso avaliar um processo por completo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["eficiência", "eficácia", "recurso", "resultado", "tma", "tempo", "recontato", "produtividade", "resolução"],
  },
  {
    slug: "tipos-de-processos",
    name: "Tipos de processo: primário, suporte e gestão",
    category: "Processos",
    summary: "Primário entrega valor direto ao cliente; suporte dá condições para o primário funcionar; gestão planeja, monitora e controla os objetivos.",
    origin: "Classificação consolidada na gestão por processos e na ISO 9001.",
    why: "Identificar o tipo do processo antes de priorizar melhorias e indicadores.",
    useWhen: ["Preciso organizar os processos da operação", "Não sei onde cada melhoria se encaixa", "Vou desenhar a arquitetura de processos"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["processo", "primário", "suporte", "gestão", "classificação", "valor", "cliente"],
  },
  {
    slug: "otimizacao-processos",
    name: "Otimização de processos",
    category: "Melhoria de processos",
    summary: "Entender, identificar, eliminar ou reduzir, melhorar e medir: mudanças que reduzem desperdício, custo e falha aumentando produtividade e qualidade.",
    origin: "Consolidada na gestão da qualidade e nas metodologias de melhoria do século XX.",
    why: "Atacar o processo que produz o defeito, não apenas o defeito final.",
    useWhen: ["O processo tem etapas duplicadas ou demora", "Custo e retrabalho subiram", "Quero ganhar produtividade sem perder qualidade"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["otimização", "melhorar", "processo", "desperdício", "custo", "produtividade", "retrabalho", "etapa"],
  },
  {
    slug: "analise-valor-agregado",
    name: "Análise de valor agregado",
    category: "Melhoria de processos",
    summary: "Separa atividades que contribuem para a entrega ao cliente daquelas que só consomem recursos. Etapas sem valor devem ser eliminadas, reduzidas, simplificadas ou automatizadas.",
    origin: "Ligada ao pensamento enxuto (lean) e à análise de processos do século XX.",
    why: "Pergunta decisiva: isto contribui para o cliente ou existe porque sempre foi feito assim?",
    useWhen: ["O fluxo tem etapas que ninguém sabe por que existem", "Quero simplificar antes de automatizar", "O processo cresceu sem revisão"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["valor agregado", "valor", "desperdício", "etapa", "simplificar", "eliminar", "cliente", "lean"],
  },
  {
    slug: "lean",
    name: "Lean",
    category: "Melhoria de processos",
    summary: "Mais valor com menos desperdício: metodologia focada em eliminar desperdícios com participação dos colaboradores. Inclui kaizen (melhorias incrementais) e just-in-time (produzir conforme a demanda, sem excesso).",
    origin: "Sistema Toyota de Produção, desenvolvido por Taiichi Ohno no Japão do pós-guerra.",
    why: "Concentrar recursos no que gera valor e envolver quem executa na identificação de desperdícios.",
    useWhen: ["Há estoque, espera, retrabalho ou movimento desnecessário", "A produção/serviço corre à frente da demanda", "Quero cultura de melhoria incremental"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "Projetos", "Operações"],
    keywords: ["lean", "desperdício", "toyota", "just in time", "kaizen", "fluxo", "produção", "enxuto"],
  },
  {
    slug: "six-sigma",
    name: "Six Sigma",
    category: "Estratégia e indicadores",
    summary: "Reduzir variabilidade e defeitos com análise de dados e estatística. Certificações em faixas: White Belt (conceitos), Yellow Belt (participa), Green Belt (lidera projetos parciais), Black Belt (lidera projetos complexos), Master Black Belt (treina e supervisiona).",
    origin: "Criado na Motorola nos anos 1980 e difundido pela General Electric nos anos 1990.",
    why: "Quando defeitos recorrentes exigem abordagem estatística estruturada, não apenas intuição.",
    useWhen: ["Defeitos se repetem sem causa clara", "A variação do processo é alta", "Preciso de rigor estatístico na melhoria"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["six sigma", "dmaic", "variabilidade", "defeito", "belt", "certificação", "estatística", "motorola"],
  },
  {
    slug: "tqm",
    name: "TQM: gestão da qualidade total",
    category: "Fundamentos",
    summary: "Qualidade como responsabilidade de toda a organização: foco no cliente, melhoria contínua, envolvimento dos colaboradores, decisão baseada em dados, liderança, pensamento em processo e sistema integrado.",
    origin: "Desenvolvido a partir do TQC de Feigenbaum e da experiência japonesa, difundido nos anos 1980.",
    why: "Integrar todas as áreas na qualidade em vez de concentrar em um time de especialistas.",
    useWhen: ["A qualidade é vista como função de um setor", "Quero espalhar a cultura de qualidade", "A direção cobra qualidade de todos"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["tqm", "qualidade total", "todos", "cultura", "cliente", "dados", "participação", "melhoria contínua"],
  },
  {
    slug: "gestao-riscos",
    name: "Gestão de riscos (ISO 31000)",
    category: "Riscos",
    summary: "Processo estruturado: contexto, identificação, análise, avaliação, tratamento, monitoramento e comunicação contínua. Antecipa problemas antes que aconteçam.",
    origin: "Norma ISO 31000, publicada inicialmente em 2009 e revisada em 2018.",
    why: "Preparar resposta a ameaças em vez de reagir quando o problema já aconteceu.",
    useWhen: ["Uma mudança de processo pode gerar efeitos indesejados", "Preciso de plano de contingência", "Quero avaliar riscos antes de um piloto"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["risco", "iso 31000", "contingência", "prevenir", "ameaça", "piloto", "impacto", "probabilidade"],
  },
  {
    slug: "gestao-projetos",
    name: "Gestão de projetos",
    category: "Plano de ação",
    summary: "Planejar, executar e controlar mudanças de forma estruturada, com objetivos, prazos, recursos e responsáveis definidos.",
    origin: "Disciplina formalizada na segunda metade do século XX, com guias como o PMBOK.",
    why: "Melhorias estruturais exigem planejamento formal, não só boa vontade.",
    useWhen: ["Uma melhoria maior precisa de cronograma e recursos", "Várias áreas precisam coordenar entregas", "O projeto envolve riscos e partes interessadas"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["projeto", "cronograma", "escopo", "prazo", "recurso", "pmi", "pmbok", "implantação"],
  },
  {
    slug: "gestao-conhecimento",
    name: "Gestão do conhecimento",
    category: "Organização",
    summary: "Capturar, organizar e disseminar conhecimento para que a operação não dependa de uma pessoa específica: documentação, base de conhecimento e treinamento contínuo.",
    origin: "Área formalizada nos anos 1990, com forte relação com a ISO 9001.",
    why: "Turnover e dependência de pessoa-chave destroem processos não documentados.",
    useWhen: ["O conhecimento fica só na cabeça das pessoas", "A base de conhecimento está desatualizada", "Preciso treinar novos analistas rápido"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["conhecimento", "documentação", "base", "turnover", "treinamento", "procedimento", "registro"],
  },
  {
    slug: "automacao-processos",
    name: "Automação de processos",
    category: "Fluxo de trabalho",
    summary: "Tecnologia executa tarefas repetitivas e demoradas com rapidez e precisão, liberando pessoas para atividades de maior valor.",
    origin: "Evolução da tecnologia da informação aplicada a processos, intensificada nos anos 2010.",
    why: "Automatizar coleta e consolidação de dados antes de automatizar decisões.",
    useWhen: ["Planilhas manuais consomem horas", "Erros de digitação se repetem", "Relatórios precisam ser gerados todo ciclo"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["automação", "robô", "planilha", "dashboard", "consolidação", "dados", "produtividade", "repetitivo"],
  },
  {
    slug: "ciclo-vida-produto",
    name: "Ciclo de vida do produto",
    category: "Cliente e produto",
    summary: "Cinco fases: desenvolvimento (requisitos e testes), introdução (garantir conformidade), crescimento (ampliar sem perder qualidade), maturidade (eficiência e inovação) e declínio (decidir retirada).",
    origin: "Conceito clássico de marketing e gestão de produtos do século XX.",
    why: "A estratégia de qualidade muda conforme a fase: conformidade no lançamento, eficiência na maturidade.",
    useWhen: ["Não sei onde o produto está no ciclo", "Vendas estabilizaram e preciso decidir o foco", "Um novo produto está sendo lançado"],
    sectors: ["Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["ciclo de vida", "produto", "lançamento", "maturidade", "declínio", "crescimento", "inovação"],
  },
  {
    slug: "sustentabilidade-organizacional",
    name: "Sustentabilidade organizacional",
    category: "Fundamentos",
    summary: "Atender necessidades atuais sem comprometer o futuro, equilibrando dimensões ambiental, social e econômica. Ganho isolado de produtividade não prova melhoria do sistema todo.",
    origin: "Conceito consolidado a partir do relatório Brundtland (1987) e incorporado à gestão.",
    why: "Avaliar se a melhoria de hoje gera desperdício, risco ou passivo amanhã.",
    useWhen: ["Uma melhoria gera resíduo ou sobrecarga", "A empresa formaliza práticas ESG", "Preciso avaliar impacto social e ambiental"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "Projetos", "Pessoas", "Operações"],
    keywords: ["sustentabilidade", "ambiental", "social", "econômico", "esg", "resíduo", "futuro", "impacto"],
  },
  {
    slug: "bpmn",
    name: "BPMN",
    category: "Processos",
    summary: "Notação gráfica padronizada para modelar processos com eventos, atividades, decisões e fluxos. Mais formal que um fluxograma comum: é uma linguagem universal de processos de negócio.",
    origin: "BPMN 1.0 publicada em 2004 pela BPM Initiative; mantida pela OMG.",
    why: "Documentar processos de forma que qualquer pessoa treinada na notação entenda.",
    useWhen: ["Preciso de documentação formal e padronizada", "Processos serão auditados ou certificados", "Diferentes áreas precisam ler o mesmo fluxo"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["bpmn", "modelagem", "notação", "documentação", "processo", "padrão", "omg", "auditoria"],
  },
  {
    slug: "vsm",
    name: "Mapeamento de fluxo de valor (VSM)",
    category: "Fluxo de trabalho",
    summary: "Desenha o fluxo de materiais e informações, compara estado atual e futuro e expõe desperdícios e esperas ao longo do valor entregue.",
    origin: "Ferramenta central do pensamento enxuto, consolidada no Sistema Toyota.",
    why: "Enxergar desperdícios no fluxo inteiro, não em etapas isoladas.",
    useWhen: ["Quero enxergar o fluxo de valor de ponta a ponta", "Há espera entre etapas", "Planejo o estado futuro do processo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "Projetos", "Operações"],
    keywords: ["vsm", "fluxo de valor", "desperdício", "espera", "lean", "mapeamento", "estado futuro"],
  },
  {
    slug: "gemba-walk",
    name: "Gemba walk",
    category: "Coleta de dados",
    summary: "Ir ao lugar onde o trabalho acontece para observar a realidade em vez de decidir só por relatórios.",
    origin: "Prática do Sistema Toyota (gemba, do japonês: o lugar real).",
    why: "Relatórios escondem o contexto: a observação direta revela o processo verdadeiro.",
    useWhen: ["Os números não explicam a queixa da equipe", "Vou propor mudança em processo que não vejo", "Quero entender gargalos na prática"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "Projetos", "Pessoas", "Operações"],
    keywords: ["gemba", "observação", "campo", "realidade", "chão de operação", "contexto", "visita"],
  },
  {
    slug: "swot",
    name: "Análise SWOT",
    category: "Estratégia e indicadores",
    summary: "Forças e fraquezas (ambiente interno) × oportunidades e ameaças (ambiente externo): quadro para analisar cenário antes de decidir estratégia.",
    origin: "Atribuída a Albert Humphrey na Stanford nos anos 1960-70.",
    why: "Decidir com visão do cenário completo, interno e externo.",
    useWhen: ["Vou definir estratégia de área", "Preciso avaliar riscos do mercado", "Planejo o próximo ciclo ou trimestre"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["swot", "forças", "fraquezas", "oportunidades", "ameaças", "cenário", "estratégia", "análise"],
  },
  {
    slug: "brainstorming",
    name: "Brainstorming",
    category: "Solução de problemas",
    summary: "Geração de ideias em grupo sem julgamento imediato, para depois organizar, priorizar e selecionar as melhores.",
    origin: "Popularizado por Alex Osborn nos anos 1930-40.",
    why: "Ampliar alternativas antes de fechar a solução e envolver a equipe na construção.",
    useWhen: ["A equipe se prende a uma única solução", "Preciso gerar hipóteses de causa", "Vou desenhar um plano com participação de todos"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["brainstorming", "ideias", "grupo", "criatividade", "hipóteses", "participação", "soluções"],
  },
  {
    slug: "fmea",
    name: "FMEA",
    category: "Riscos",
    summary: "Análise de modos de falha e seus efeitos: pontua severidade, ocorrência e detecção para priorizar onde prevenir. O PFMEA aplica a mesma lógica a processos.",
    origin: "Nasceu em 1949 com o Exército dos EUA (MIL-P-1629), passou pela NASA (Apollo) e pela indústria automotiva nos anos 1970.",
    why: "Prever onde o processo pode falhar antes que aconteça, com pontuação objetiva.",
    useWhen: ["Quero prever falhas antes de implantar", "Um produto crítico será lançado", "Preciso priorizar modos de falha"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["fmea", "falha", "severidade", "ocorrência", "detecção", "rpn", "prevenção", "risco"],
  },
  {
    slug: "kaizen",
    name: "Kaizen",
    category: "Melhoria contínua",
    summary: "Mudança para melhor: pequenas melhorias incrementais e contínuas, feitas por todos, todos os dias, em vez de grandes projetos isolados.",
    origin: "Prática japonesa do pós-guerra, associada a Masaaki Imai e ao Sistema Toyota.",
    why: "Sustentar evolução constante com baixo custo e engajamento de quem executa.",
    useWhen: ["Quero melhorar continuamente sem grandes projetos", "A equipe pode propor melhorias próprias", "Pequenos ajustes somam resultado"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["kaizen", "melhoria contínua", "incremental", "pequenas melhorias", "cultura", "evolução", "japão"],
  },
  {
    slug: "iso-9001",
    name: "ISO 9001:2015",
    category: "Normas e conformidade",
    summary: "Norma de sistemas de gestão da qualidade baseada em ciclo PDCA, pensamento baseado em riscos e melhoria contínua: mapear processos, definir política e objetivos, documentar, auditar e revisar.",
    origin: "Publicada pela ISO em 2015, sucedendo versões desde 1987.",
    why: "Estruturar o sistema de gestão e abrir caminho para certificação e credibilidade de mercado.",
    useWhen: ["A empresa busca certificação", "Preciso estruturar documentação de qualidade", "Clientes exigem sistema de gestão formal"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["iso 9001", "norma", "certificação", "sgq", "documentação", "auditoria", "pdca", "risco"],
  },
  {
    slug: "auditoria-interna",
    name: "Auditoria interna de qualidade",
    summary: "Verificação planejada e independente de processos e registros contra critérios definidos, com plano de ação para os achados.",
    origin: "Requisito consolidado nas normas de sistemas de gestão (série ISO 9000).",
    category: "Normas e conformidade",
    why: "Detectar desvios antes do cliente ou do certificador e alimentar a melhoria com evidências.",
    useWhen: ["Preciso verificar aderência aos procedimentos", "Preparo para auditoria externa", "Avaliativos de ciclo precisam de método"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["auditoria", "interna", "verificação", "achados", "plano de ação", "conformidade", "auditor"],
  },
  {
    slug: "gestao-nao-conformidades",
    name: "Gestão de não conformidades",
    category: "Riscos",
    summary: "Tratar desvios com fluxo completo: identificar, registrar, analisar causa, tratar, prevenir e acompanhar a eficácia da ação.",
    origin: "Requisito das normas de gestão da qualidade e prática consolidada de SGQ.",
    why: "Sem fluxo estruturado, desvios viram reclamação sem aprendizado nem prevenção.",
    useWhen: ["Desvios são registrados e nunca tratados", "O mesmo erro retorna após correção", "Preciso demonstrar eficácia das ações"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["não conformidade", "nc", "desvio", "tratativa", "prevenção", "ação corretiva", "reincidência", "reclamação"],
  },
];

export const problemGuides: ProblemGuide[] = [
  {
    problem: "A comunicação entre áreas ou com o cliente está falhando",
    context: "Mensagens contraditórias, repasses incompletos, registro ruim ou expectativas desalinhadas.",
    outcome: "Mapear onde a informação se perde, encontrar a causa e definir um padrão de comunicação.",
    toolSlugs: ["fluxograma", "sipoc", "ishikawa", "5w2h"],
    keywords: ["problema de comunicação", "falha de comunicação", "ruído", "informação", "repasses", "alinhamento", "atendimento"],
  },
  {
    problem: "As vendas caíram ou a conversão está baixa",
    context: "O funil tem perdas, mas ainda não está claro em qual etapa e por qual motivo.",
    outcome: "Medir o funil, priorizar perdas e testar relações entre abordagem, prazo, preço e conversão.",
    toolSlugs: ["fluxograma", "pareto", "dispersao", "pdca", "indicadores"],
    keywords: ["vendas", "aumentar vendas", "melhorar vendas", "queda de vendas", "conversão", "prospecção", "proposta", "funil", "lead", "negociação"],
  },
  {
    problem: "Estamos perdendo clientes ou aumentando cancelamentos",
    context: "Churn, reclamações, abandono ou queda de recompra sem uma causa comprovada.",
    outcome: "Classificar motivos, priorizar causas e relacionar experiência, produto e comportamento do cliente.",
    toolSlugs: ["folha-verificacao", "pareto", "5-porques", "qfd", "dispersao"],
    keywords: ["perda de cliente", "cliente saindo", "churn", "cancelamento", "retenção", "recompra", "abandono"],
  },
  {
    problem: "O atendimento varia muito entre pessoas ou canais",
    context: "Clientes recebem respostas, prazos ou condutas diferentes para situações semelhantes.",
    outcome: "Definir o processo, medir ocorrências e acompanhar se a variação diminui.",
    toolSlugs: ["fluxograma", "folha-verificacao", "msa", "carta-controle", "pdca"],
    keywords: ["atendimento", "suporte", "chat", "telefone", "e-mail", "qualidade técnica", "padronização", "cliente"],
  },
  {
    problem: "O e-commerce tem atrasos, devoluções ou abandono de carrinho",
    context: "A jornada envolve site, pagamento, estoque, entrega e atendimento, com falhas em diferentes pontos.",
    outcome: "Enxergar a jornada, priorizar ocorrências e antecipar modos de falha.",
    toolSlugs: ["sipoc", "fluxograma", "pareto", "pfmea", "fmea-poka-yoke"],
    keywords: ["e-commerce", "carrinho", "checkout", "pagamento", "devolução", "entrega", "atraso", "estoque"],
  },
  {
    problem: "Preciso medir resultados e trabalhar com números",
    context: "Existem dados, mas faltam métricas confiáveis, leitura estatística ou uma linha de base.",
    outcome: "Definir indicadores e escolher a análise adequada para distribuição, relação ou estabilidade.",
    toolSlugs: ["indicadores", "folha-verificacao", "histograma", "dispersao", "carta-controle"],
    keywords: ["medição", "métrica", "número", "estatística", "dados", "kpi", "indicador", "meta", "resultado"],
  },
  {
    problem: "Um projeto ou implantação pode falhar",
    context: "Há dependências, mudanças de processo, fornecedores ou riscos antes da entrada em produção.",
    outcome: "Delimitar o processo, avaliar riscos e transformar respostas em ações com dono e prazo.",
    toolSlugs: ["sipoc", "matriz-risco", "pfmea", "5w2h", "kanban"],
    keywords: ["projeto", "implantação", "go live", "risco", "prazo", "escopo", "dependência", "fornecedor"],
  },
  {
    problem: "A empresa está perdendo pessoas ou tem alta rotatividade",
    context: "Saídas, absenteísmo ou queda de desempenho podem ter múltiplas causas e vieses de percepção.",
    outcome: "Estruturar dados de saída, priorizar motivos e investigar causas de processo e ambiente.",
    toolSlugs: ["folha-verificacao", "pareto", "ishikawa", "5-porques", "dispersao"],
    keywords: ["perda de funcionário", "turnover", "rotatividade", "demissão", "absenteísmo", "clima", "pessoas", "retenção"],
  },
  {
    problem: "Existem problemas demais e tudo parece urgente",
    context: "A equipe reage ao que chegou por último e não consegue justificar a sequência de tratamento.",
    outcome: "Criar uma prioridade defensável e organizar a execução.",
    toolSlugs: ["pareto", "gut", "kanban", "5w2h"],
    keywords: ["muitos problemas", "prioridade", "urgente", "backlog", "fila", "organização", "plano de ação"],
  },
  {
    problem: "Quero comprovar que a melhoria funcionou",
    context: "Uma mudança foi implantada, mas a equipe ainda não comparou o antes e o depois nem verificou estabilidade.",
    outcome: "Definir medida, acompanhar a tendência e incorporar o resultado ao padrão.",
    toolSlugs: ["pdca", "indicadores", "carta-controle", "histograma", "a3"],
    keywords: ["melhoria", "resultado", "antes e depois", "eficácia", "meta", "comprovar", "evolução"],
  },
  {
    problem: "O processo é desorganizado e ninguém sabe como ele funciona de verdade",
    context: "Cada pessoa executa de um jeito e o fluxo real nunca foi desenhado.",
    outcome: "Tornar o processo visível, mapear o fluxo real e padronizar o que importa.",
    toolSlugs: ["fluxograma", "sipoc", "bpmn", "tipos-de-processos"],
    keywords: ["processo desorganizado", "caos", "ninguém sabe", "fluxo", "padronizar", "mapear"],
  },
  {
    problem: "O ambiente ou a documentação está bagunçado",
    context: "Arquivos, materiais e informações se acumulam sem critério de uso e organização.",
    outcome: "Aplicar os sensos para eliminar o desnecessário e manter a organização viva.",
    toolSlugs: ["5s", "gestao-conhecimento"],
    keywords: ["bagunçado", "organização", "documentação", "arquivos", "5s", "limpeza"],
  },
  {
    problem: "O plano de ação ficou vago, sem responsável nem prazo",
    context: "Ações genéricas como melhorar atendimento não geram execução nem verificação.",
    outcome: "Estruturar cada ação com o quê, por quê, quem, quando, onde, como e quanto custa.",
    toolSlugs: ["5w2h", "pdca", "gestao-projetos"],
    keywords: ["plano de ação", "vago", "responsável", "prazo", "5w2h", "execução", "compromisso"],
  },
  {
    problem: "Preciso alinhar o escopo de um processo antes de melhorá-lo",
    context: "Melhorar sem definir fornecedores, entradas, saídas e clientes gera escopo impreciso.",
    outcome: "Desenhar a visão macro e validar limites antes de detalhar o fluxo.",
    toolSlugs: ["sipoc", "fluxograma", "tipos-de-processos"],
    keywords: ["escopo", "macro", "sipoc", "fornecedores", "entradas", "saídas", "clientes"],
  },
  {
    problem: "Quero traduzir a estratégia da empresa em indicadores",
    context: "A estratégia existe no discurso, mas não chega às áreas como metas acompanháveis.",
    outcome: "Conectar objetivos a indicadores nas perspectivas financeira, cliente, processos e aprendizado.",
    toolSlugs: ["bsc", "indicadores", "swot"],
    keywords: ["estratégia", "indicadores", "bsc", "metas", "objetivos", "perspectivas"],
  },
  {
    problem: "A qualidade está isolada em uma equipe, não é responsabilidade de todos",
    context: "Outras áreas veem qualidade como serviço dos inspetores e não aplicam padrões.",
    outcome: "Distribuir a responsabilidade pela qualidade por toda a organização.",
    toolSlugs: ["tqm", "feigenbaum", "ishikawa-fundamentos", "deming"],
    keywords: ["qualidade de todos", "isolada", "tqm", "cultura", "participação", "responsabilidade"],
  },
  {
    problem: "A empresa acha que qualidade é só inspeção no final",
    context: "Descobrir defeito no fim consome recursos: matéria-prima, tempo e energia já gastos.",
    outcome: "Mudar para prevenção: prevenir custa menos que corrigir continuamente.",
    toolSlugs: ["gestao-qualidade-visao-geral", "crosby", "fmea", "fmea-poka-yoke"],
    keywords: ["inspeção", "no final", "prevenção", "defeito", "custo", "qualidade"],
  },
  {
    problem: "Preciso justificar investimento em qualidade para a direção",
    context: "Qualidade é vista como custo, não como retorno.",
    outcome: "Demonstrar o custo da não qualidade e o retorno da prevenção com números.",
    toolSlugs: ["crosby", "indicadores", "iso-9001", "eficiencia-eficacia"],
    keywords: ["investimento", "custo", "retorno", "direção", "justificar", "orçamento"],
  },
  {
    problem: "O resultado foi bom, mas pode não se sustentar",
    context: "A meta foi batida com sobrecarga, improviso ou dependência de uma pessoa-chave.",
    outcome: "Avaliar se o desempenho é sustentável e separar eficiência de eficácia.",
    toolSlugs: ["excelencia-organizacional", "eficiencia-eficacia", "carta-controle", "gestao-conhecimento"],
    keywords: ["sustentar", "frágil", "sobrecarga", "pessoa-chave", "sustentável", "excelência"],
  },
  {
    problem: "Não sei se um risco pode virar problema antes de acontecer",
    context: "Mudanças e processos têm ameaças não avaliadas nem plano de resposta.",
    outcome: "Identificar, avaliar e tratar riscos antes do impacto, com monitoramento contínuo.",
    toolSlugs: ["gestao-riscos", "matriz-risco", "pfmea", "fmea"],
    keywords: ["risco", "antes", "prevenir", "antecipar", "contingência", "impacto"],
  },
  {
    problem: "Quero organizar a área de qualidade como um sistema",
    context: "Critérios, avaliações, indicadores e planos existem, mas soltos e sem ciclo.",
    outcome: "Estruturar planejamento, controle e melhoria como um ciclo de gestão.",
    toolSlugs: ["juran-trilogia", "iso-9001", "implantar-gestao-qualidade"],
    keywords: ["sistema", "organizar", "área de qualidade", "trilogia", "estrutura", "ciclo"],
  },
  {
    problem: "Preciso documentar processos de forma formal e padronizada",
    context: "Cada setor documenta de um jeito e ninguém confia nos registros.",
    outcome: "Adotar uma notação única e manter a documentação viva.",
    toolSlugs: ["bpmn", "gestao-conhecimento", "iso-9001"],
    keywords: ["documentar", "padronizada", "bpmn", "notação", "registro", "formal"],
  },
];

export function toolBySlug(slug: string) {
  return qualityTools.find((tool) => tool.slug === slug);
}
