export type QualityTool = {
  slug: string;
  name: string;
  category: string;
  summary: string;
  origin: string;
  why: string;
  useWhen: string[];
  sectors: string[];
  keywords: string[];
};

export type ProblemGuide = {
  problem: string;
  context: string;
  outcome: string;
  toolSlugs: string[];
  keywords: string[];
};

export const sectors = [
  "Todos",
  "Atendimento",
  "Vendas",
  "E-commerce",
  "SaaS e tecnologia",
  "Projetos",
  "Riscos",
  "Pessoas",
  "Operações",
];

export const qualityTools: QualityTool[] = [
  {
    slug: "fluxograma",
    name: "Fluxograma",
    category: "Processos",
    summary: "Representa as etapas e decisões de um processo para revelar falhas, esperas e retrabalho.",
    origin: "Frank e Lillian Gilbreth apresentaram o gráfico de processo à ASME em 1921. A notação evoluiu depois.",
    why: "Tornar o trabalho real visível antes de tentar padronizar ou melhorar.",
    useWhen: ["Ninguém concorda sobre como o processo funciona", "Há etapas duplicadas, demora ou repasse excessivo", "É preciso treinar ou documentar um fluxo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["comunicação", "passagem de bastão", "jornada", "funil", "checkout", "processo desorganizado", "retrabalho", "implantação"],
  },
  {
    slug: "ishikawa",
    name: "Diagrama de Ishikawa",
    category: "Causa raiz",
    summary: "Organiza causas possíveis de um efeito em grupos para orientar uma investigação baseada em evidências.",
    origin: "Associado a Kaoru Ishikawa e difundido no Japão a partir da década de 1940.",
    why: "Evitar soluções apressadas que tratam apenas o sintoma.",
    useWhen: ["Um erro se repete", "Há muitas hipóteses sobre a causa", "Uma falha envolve pessoas, método, tecnologia ou ambiente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["comunicação", "cliente insatisfeito", "queda de vendas", "turnover", "falha", "erro", "causa", "6m"],
  },
  {
    slug: "folha-verificacao",
    name: "Folha de verificação",
    category: "Coleta de dados",
    summary: "Registra ocorrências no momento em que acontecem usando categorias consistentes e fáceis de contar.",
    origin: "Consolidada entre as sete ferramentas básicas da qualidade no século XX. Não há um único criador consensual.",
    why: "Transformar percepções soltas em dados comparáveis.",
    useWhen: ["Você precisa saber quantas vezes algo acontece", "Os dados vêm de várias pessoas", "É necessário preparar uma análise de Pareto"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Riscos", "Pessoas", "Operações"],
    keywords: ["medição", "contagem", "ocorrência", "elogio", "reclamação", "motivo de contato", "perda de cliente", "dados"],
  },
  {
    slug: "pareto",
    name: "Diagrama de Pareto",
    category: "Priorização",
    summary: "Ordena causas ou ocorrências por frequência ou impacto e mostra o percentual acumulado.",
    origin: "Joseph Juran aplicou o princípio de Pareto à gestão da qualidade em meados do século XX.",
    why: "Concentrar esforço nas poucas causas que respondem pela maior parte do efeito.",
    useWhen: ["Há problemas demais para tratar ao mesmo tempo", "Você quer priorizar motivos de perda ou reclamação", "Precisa justificar uma prioridade com números"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["vendas", "perda de cliente", "churn", "cancelamento", "reclamação", "defeito", "80 20", "prioridade", "atraso"],
  },
  {
    slug: "histograma",
    name: "Histograma",
    category: "Estatística",
    summary: "Mostra como valores numéricos se distribuem por faixas, revelando concentração, dispersão e assimetria.",
    origin: "Karl Pearson introduziu o termo histograma em 1895.",
    why: "Entender a forma e a variação dos dados antes de concluir pela média.",
    useWhen: ["Você tem muitos valores numéricos", "Quer comparar tempo, nota, ticket ou produtividade", "Precisa verificar dispersão e valores extremos"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["estatística", "número", "dados", "distribuição", "tempo médio", "nota", "ticket médio", "produtividade", "medição"],
  },
  {
    slug: "carta-controle",
    name: "Carta de controle",
    category: "Estatística",
    summary: "Acompanha uma medida no tempo e diferencia variação comum de sinais que exigem investigação.",
    origin: "Walter A. Shewhart desenvolveu os gráficos de controle nos Bell Labs na década de 1920.",
    why: "Controlar processos com base em comportamento ao longo do tempo, sem reagir a cada oscilação isolada.",
    useWhen: ["É preciso saber se o processo está estável", "Você acompanha uma métrica por semana ou mês", "Quer verificar se uma melhoria permaneceu"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Operações"],
    keywords: ["estatística", "indicador", "tendência", "meta", "variação", "tempo", "conversão", "qualidade", "estabilidade"],
  },
  {
    slug: "dispersao",
    name: "Diagrama de dispersão",
    category: "Estatística",
    summary: "Compara pares de valores para investigar se duas variáveis parecem se mover juntas.",
    origin: "Deriva dos estudos de correlação do fim do século XIX, associados a Francis Galton e Karl Pearson.",
    why: "Testar uma hipótese de relação antes de afirmar causa e efeito.",
    useWhen: ["Você suspeita que uma variável influencia outra", "Quer comparar treinamento e desempenho", "Precisa investigar preço, prazo, satisfação ou conversão"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["correlação", "vendas", "satisfação", "conversão", "treinamento", "produtividade", "estatística", "dados", "churn"],
  },
  {
    slug: "sipoc",
    name: "SIPOC",
    category: "Processos",
    summary: "Delimita fornecedores, entradas, processo, saídas e clientes em uma visão de alto nível.",
    origin: "Difundido por programas de melhoria de processos e Six Sigma no fim do século XX.",
    why: "Alinhar rapidamente o escopo e as interfaces antes de detalhar o processo.",
    useWhen: ["Um projeto começa sem escopo claro", "Há conflito entre áreas", "Você precisa entender quem entrega o quê para quem"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["comunicação entre áreas", "handoff", "fornecedor", "cliente", "escopo", "implantação", "processo"],
  },
  {
    slug: "kanban",
    name: "Kanban",
    category: "Fluxo de trabalho",
    summary: "Visualiza demandas em andamento e limita trabalho simultâneo para melhorar fluxo e previsibilidade.",
    origin: "Taiichi Ohno desenvolveu o sistema kanban na Toyota entre as décadas de 1940 e 1950.",
    why: "Expor filas, bloqueios e excesso de trabalho iniciado.",
    useWhen: ["Existem tarefas paradas ou esquecidas", "A equipe inicia mais do que consegue terminar", "Falta visibilidade de prazos e responsáveis"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["tarefa", "prazo", "fila", "backlog", "projeto", "atendimento", "organização", "comunicação"],
  },
  {
    slug: "5s",
    name: "5S",
    category: "Organização",
    summary: "Cria disciplina para separar, ordenar, limpar, padronizar e sustentar um ambiente de trabalho.",
    origin: "Sistematizado no Japão do pós-guerra. A literatura não atribui uma única data ou autoria.",
    why: "Reduzir perdas causadas por desorganização física ou digital.",
    useWhen: ["Documentos e informações são difíceis de encontrar", "O ambiente causa erros ou desperdício", "Uma equipe precisa de padrões simples de organização"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["organização", "documentos", "arquivos", "ambiente", "padronização", "desperdício"],
  },
  {
    slug: "matriz-risco",
    name: "Matriz de risco",
    category: "Riscos",
    summary: "Classifica riscos combinando probabilidade e impacto para orientar resposta e prioridade.",
    origin: "Consolidada em segurança, defesa e engenharia ao longo do século XX, com diversas versões.",
    why: "Dar um critério comum para decidir quais incertezas exigem ação.",
    useWhen: ["Um projeto ou mudança ainda não começou", "Há riscos operacionais ou de segurança", "É preciso decidir entre aceitar, mitigar, transferir ou evitar"],
    sectors: ["E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["risco", "projeto", "implantação", "segurança", "impacto", "probabilidade", "prevenção", "fornecedor"],
  },
  {
    slug: "pfmea",
    name: "PFMEA",
    category: "Riscos",
    summary: "Analisa modos de falha de um processo, seus efeitos, causas, controles atuais e ações preventivas.",
    origin: "FMEA surgiu em aplicações militares e aeroespaciais do pós-guerra. A variante de processo se difundiu depois na indústria automotiva.",
    why: "Prevenir falhas antes que cheguem ao cliente ou interrompam a operação.",
    useWhen: ["Você desenha ou altera um processo", "Uma falha pode ter alto impacto", "É preciso revisar controles preventivos e de detecção"],
    sectors: ["E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["falha", "risco", "e-commerce", "checkout", "implantação", "severidade", "ocorrência", "detecção"],
  },
  {
    slug: "5-porques",
    name: "5 Porquês",
    category: "Causa raiz",
    summary: "Aprofunda uma cadeia causal perguntando por que o problema aconteceu até chegar a uma causa tratável.",
    origin: "Associado ao Sistema Toyota de Produção e ao trabalho de Taiichi Ohno no século XX.",
    why: "Sair da explicação superficial e encontrar uma ação que evite recorrência.",
    useWhen: ["O problema é específico e a equipe conhece o processo", "Uma ocorrência se repete", "Você precisa de uma investigação inicial rápida"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["comunicação", "causa raiz", "erro", "reclamação", "perda de cliente", "turnover", "atraso", "falha"],
  },
  {
    slug: "5w2h",
    name: "5W2H",
    category: "Plano de ação",
    summary: "Converte uma decisão em ação ao definir o que, por que, onde, quando, quem, como e quanto custa.",
    origin: "Técnica de planejamento difundida no século XX. A origem exata não é consensual.",
    why: "Eliminar planos vagos, sem dono, prazo ou modo de execução.",
    useWhen: ["A equipe já entendeu a causa e precisa agir", "Há dúvidas sobre responsabilidade ou prazo", "Um projeto precisa de um plano simples"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["plano de ação", "responsável", "prazo", "custo", "projeto", "melhoria", "implantação", "vendas"],
  },
  {
    slug: "masp",
    name: "MASP",
    category: "Solução de problemas",
    summary: "Estrutura a identificação, análise, ação, verificação e padronização da solução de um problema.",
    origin: "Adaptação brasileira do QC Story, difundida a partir da década de 1980.",
    why: "Conduzir problemas relevantes com disciplina e registro do aprendizado.",
    useWhen: ["O problema exige investigação completa", "Várias áreas participam da solução", "É necessário comprovar eficácia e padronizar"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["problema", "causa", "ação corretiva", "melhoria", "resultado", "padronização", "reclamação"],
  },
  {
    slug: "dmaic",
    name: "DMAIC",
    category: "Melhoria de processos",
    summary: "Organiza projetos em definir, medir, analisar, melhorar e controlar, com uso disciplinado de dados.",
    origin: "Ligado ao Six Sigma da Motorola nos anos 1980 e difundido amplamente nos anos 1990.",
    why: "Melhorar processos existentes quando o problema e o desempenho precisam ser quantificados.",
    useWhen: ["Há impacto mensurável e dados disponíveis", "A causa ainda não está comprovada", "A melhoria precisa ser sustentada por controles"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Operações"],
    keywords: ["dados", "estatística", "vendas", "conversão", "tempo", "defeito", "melhoria", "six sigma"],
  },
  {
    slug: "pdca",
    name: "PDCA",
    category: "Melhoria contínua",
    summary: "Cria um ciclo de planejar, executar, verificar resultados e agir para ajustar ou padronizar.",
    origin: "Deriva do ciclo de Shewhart dos anos 1930 e ganhou projeção com W. Edwards Deming.",
    why: "Transformar melhoria em um processo contínuo de teste e aprendizado.",
    useWhen: ["Você precisa testar uma melhoria", "Existe uma meta e um indicador", "A solução precisa virar padrão"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["melhoria", "indicador", "meta", "teste", "plano", "resultado", "padronização", "qualidade"],
  },
  {
    slug: "a3",
    name: "Kaizen A3",
    category: "Melhoria contínua",
    summary: "Registra contexto, análise, objetivo, contramedidas e acompanhamento de uma melhoria em uma narrativa concisa.",
    origin: "Desenvolvido na Toyota e nomeado pelo formato de papel A3 usado para comunicar o raciocínio.",
    why: "Tornar o pensamento por trás da melhoria claro e compartilhável.",
    useWhen: ["É preciso alinhar liderança e equipe", "O problema cabe em um projeto de melhoria focado", "Você quer registrar decisão e acompanhamento"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["kaizen", "melhoria", "comunicação", "projeto", "relatório", "causa", "plano"],
  },
  {
    slug: "gut",
    name: "Matriz GUT",
    category: "Priorização",
    summary: "Compara problemas por gravidade, urgência e tendência usando uma escala comum.",
    origin: "Popular na gestão brasileira. A atribuição histórica varia e não há origem única bem documentada.",
    why: "Criar uma ordem de ataque quando diferentes problemas competem por atenção.",
    useWhen: ["Tudo parece urgente", "A equipe precisa negociar prioridades", "Há riscos ou problemas qualitativos difíceis de comparar"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["prioridade", "urgência", "gravidade", "risco", "problema", "backlog", "plano"],
  },
  {
    slug: "bsc",
    name: "Balanced Scorecard",
    category: "Estratégia e indicadores",
    summary: "Conecta objetivos, indicadores, metas e iniciativas nas perspectivas financeira, clientes, processos e aprendizado.",
    origin: "Robert Kaplan e David Norton apresentaram o Balanced Scorecard em 1992.",
    why: "Traduzir estratégia em medidas equilibradas, além do resultado financeiro isolado.",
    useWhen: ["A empresa precisa alinhar indicadores à estratégia", "Há métricas sem relação clara com objetivos", "A liderança quer acompanhar execução de longo prazo"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Pessoas", "Operações"],
    keywords: ["indicador", "kpi", "vendas", "cliente", "financeiro", "estratégia", "meta", "medição"],
  },
  {
    slug: "indicadores",
    name: "Indicadores de qualidade",
    category: "Medição",
    summary: "Traduzem objetivos em medidas com fórmula, fonte, frequência, responsável e interpretação definidas.",
    origin: "Prática consolidada em gestão e controle ao longo do século XX, sem um único criador.",
    why: "Acompanhar desempenho e tomar decisões usando critérios consistentes.",
    useWhen: ["Uma meta está vaga", "Você precisa demonstrar evolução", "A equipe coleta números mas não sabe o que eles significam"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Pessoas", "Operações"],
    keywords: ["medição", "kpi", "número", "dados", "meta", "conversão", "satisfação", "churn", "tempo", "estatística"],
  },
  {
    slug: "qfd",
    name: "QFD",
    category: "Cliente e produto",
    summary: "Converte necessidades do cliente em requisitos técnicos e prioridades de produto ou serviço.",
    origin: "Desenvolvido no Japão no fim dos anos 1960 por Yoji Akao e Shigeru Mizuno.",
    why: "Evitar que a solução técnica se afaste do que o cliente realmente valoriza.",
    useWhen: ["Você desenha um produto ou serviço", "Clientes reclamam de aspectos diferentes", "É preciso priorizar requisitos a partir da voz do cliente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Projetos"],
    keywords: ["cliente", "vendas", "satisfação", "necessidade", "produto", "requisito", "experiência", "pesquisa"],
  },
  {
    slug: "8d",
    name: "8D",
    category: "Solução de problemas",
    summary: "Conduz resposta em equipe, contenção, causa raiz, correção, prevenção e reconhecimento do aprendizado.",
    origin: "Popularizado pela Ford na década de 1980, com raízes em práticas anteriores de resolução estruturada.",
    why: "Controlar rapidamente um problema relevante sem abandonar a investigação definitiva.",
    useWhen: ["O cliente sofre impacto agora", "É necessária contenção imediata", "O problema é complexo e recorrente"],
    sectors: ["Atendimento", "E-commerce", "SaaS e tecnologia", "Projetos", "Riscos", "Operações"],
    keywords: ["reclamação", "incidente", "contenção", "falha", "cliente", "ação corretiva", "recorrência"],
  },
  {
    slug: "msa",
    name: "MSA e estudo R&R",
    category: "Medição",
    summary: "Avalia se o sistema de medição produz resultados consistentes entre pessoas, instrumentos e repetições.",
    origin: "Consolidado na indústria automotiva e em manuais de análise de sistemas de medição no fim do século XX.",
    why: "Separar variação real do processo da variação criada pela própria medição.",
    useWhen: ["A equipe não confia nas notas ou avaliações", "Avaliadores discordam muito", "Um indicador depende de julgamento ou instrumento"],
    sectors: ["Atendimento", "SaaS e tecnologia", "Pessoas", "Operações"],
    keywords: ["calibragem", "avaliação", "nota", "medição", "concordância", "dados", "estatística", "auditoria"],
  },
  {
    slug: "fmea-poka-yoke",
    name: "Poka-yoke",
    category: "Prevenção de erros",
    summary: "Usa mecanismos simples para impedir um erro ou torná-lo imediatamente visível.",
    origin: "Associado a Shigeo Shingo e ao Sistema Toyota de Produção na década de 1960.",
    why: "Projetar o processo para reduzir dependência de atenção e memória.",
    useWhen: ["O mesmo erro humano reaparece", "Uma validação pode ser automatizada", "A falha precisa ser detectada antes de chegar ao cliente"],
    sectors: ["Atendimento", "Vendas", "E-commerce", "SaaS e tecnologia", "Operações"],
    keywords: ["erro humano", "validação", "formulário", "sistema", "checkout", "prevenção", "automação"],
  },
];

export const problemGuides: ProblemGuide[] = [
  {
    problem: "A comunicação entre áreas ou com o cliente está falhando",
    context: "Mensagens contraditórias, repasses incompletos, registro ruim ou expectativas desalinhadas.",
    outcome: "Mapear onde a informação se perde, encontrar a causa e definir um padrão de comunicação.",
    toolSlugs: ["fluxograma", "sipoc", "ishikawa", "5w2h"],
    keywords: ["problema de comunicação", "falha de comunicação", "ruído", "informação", "repasses", "alinhamento", "atendimento"],
  },
  {
    problem: "As vendas caíram ou a conversão está baixa",
    context: "O funil tem perdas, mas ainda não está claro em qual etapa e por qual motivo.",
    outcome: "Medir o funil, priorizar perdas e testar relações entre abordagem, prazo, preço e conversão.",
    toolSlugs: ["fluxograma", "pareto", "dispersao", "pdca", "indicadores"],
    keywords: ["vendas", "aumentar vendas", "melhorar vendas", "queda de vendas", "conversão", "prospecção", "proposta", "funil", "lead", "negociação"],
  },
  {
    problem: "Estamos perdendo clientes ou aumentando cancelamentos",
    context: "Churn, reclamações, abandono ou queda de recompra sem uma causa comprovada.",
    outcome: "Classificar motivos, priorizar causas e relacionar experiência, produto e comportamento do cliente.",
    toolSlugs: ["folha-verificacao", "pareto", "5-porques", "qfd", "dispersao"],
    keywords: ["perda de cliente", "cliente saindo", "churn", "cancelamento", "retenção", "recompra", "abandono"],
  },
  {
    problem: "O atendimento varia muito entre pessoas ou canais",
    context: "Clientes recebem respostas, prazos ou condutas diferentes para situações semelhantes.",
    outcome: "Definir o processo, medir ocorrências e acompanhar se a variação diminui.",
    toolSlugs: ["fluxograma", "folha-verificacao", "msa", "carta-controle", "pdca"],
    keywords: ["atendimento", "suporte", "chat", "telefone", "e-mail", "qualidade técnica", "padronização", "cliente"],
  },
  {
    problem: "O e-commerce tem atrasos, devoluções ou abandono de carrinho",
    context: "A jornada envolve site, pagamento, estoque, entrega e atendimento, com falhas em diferentes pontos.",
    outcome: "Enxergar a jornada, priorizar ocorrências e antecipar modos de falha.",
    toolSlugs: ["sipoc", "fluxograma", "pareto", "pfmea", "fmea-poka-yoke"],
    keywords: ["e-commerce", "carrinho", "checkout", "pagamento", "devolução", "entrega", "atraso", "estoque"],
  },
  {
    problem: "Preciso medir resultados e trabalhar com números",
    context: "Existem dados, mas faltam métricas confiáveis, leitura estatística ou uma linha de base.",
    outcome: "Definir indicadores e escolher a análise adequada para distribuição, relação ou estabilidade.",
    toolSlugs: ["indicadores", "folha-verificacao", "histograma", "dispersao", "carta-controle"],
    keywords: ["medição", "métrica", "número", "estatística", "dados", "kpi", "indicador", "meta", "resultado"],
  },
  {
    problem: "Um projeto ou implantação pode falhar",
    context: "Há dependências, mudanças de processo, fornecedores ou riscos antes da entrada em produção.",
    outcome: "Delimitar o processo, avaliar riscos e transformar respostas em ações com dono e prazo.",
    toolSlugs: ["sipoc", "matriz-risco", "pfmea", "5w2h", "kanban"],
    keywords: ["projeto", "implantação", "go live", "risco", "prazo", "escopo", "dependência", "fornecedor"],
  },
  {
    problem: "A empresa está perdendo pessoas ou tem alta rotatividade",
    context: "Saídas, absenteísmo ou queda de desempenho podem ter múltiplas causas e vieses de percepção.",
    outcome: "Estruturar dados de saída, priorizar motivos e investigar causas de processo e ambiente.",
    toolSlugs: ["folha-verificacao", "pareto", "ishikawa", "5-porques", "dispersao"],
    keywords: ["perda de funcionário", "turnover", "rotatividade", "demissão", "absenteísmo", "clima", "pessoas", "retenção"],
  },
  {
    problem: "Existem problemas demais e tudo parece urgente",
    context: "A equipe reage ao que chegou por último e não consegue justificar a sequência de tratamento.",
    outcome: "Criar uma prioridade defensável e organizar a execução.",
    toolSlugs: ["pareto", "gut", "kanban", "5w2h"],
    keywords: ["muitos problemas", "prioridade", "urgente", "backlog", "fila", "organização", "plano de ação"],
  },
  {
    problem: "Quero comprovar que a melhoria funcionou",
    context: "Uma mudança foi implantada, mas a equipe ainda não comparou o antes e o depois nem verificou estabilidade.",
    outcome: "Definir medida, acompanhar a tendência e incorporar o resultado ao padrão.",
    toolSlugs: ["pdca", "indicadores", "carta-controle", "histograma", "a3"],
    keywords: ["melhoria", "resultado", "antes e depois", "eficácia", "meta", "comprovar", "evolução"],
  },
];

export function toolBySlug(slug: string) {
  return qualityTools.find((tool) => tool.slug === slug);
}
